# Render Deployment Configuration
# This file configures the deployment settings for Render.com

# Web Service Configuration
services:
  - type: web
    name: admin-dashboard-rbac
    runtime: node
    plan: free
    region: oregon
    branch: main

    # Build Configuration
    buildCommand: |
      cd backend
      npm ci --only=production
      npm run build

    # Start Command
    startCommand: |
      cd backend
      npm start

    # Health Check
    healthCheckPath: /health

    # Auto Deploy
    autoDeploy: true

    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        value: https://admin-dashboard-rbac.onrender.com

# Database Configuration (Optional - if using Render's MongoDB)
databases:
  - name: mongodb-atlas
    plan: free
    region: oregon
